name: CD - Docker

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  docker:
    name: Build imagem Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: financaspro:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verificar imagem
        run: docker images financaspro:${{ github.sha }}
